AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Devcon Schedule lambda
Resources:
  devconSchedule:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 5
      Runtime: nodejs6.10
      Handler: index.handler
      CodeUri: .
  # scheduleApi:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Timeout: 5
  #     Runtime: nodejs6.10
  #     Handler: schedule.handler
  #     CodeUri: .
